# Generated by Django 4.1.2 on 2022-11-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeiboapp', '0002_want'),
    ]

    operations = [
        migrations.RenameField(
            model_name='want',
            old_name='date_buy',
            new_name='date',
        ),
    ]
