# Generated by Django 4.1.2 on 2022-10-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='who', max_length=30, unique=True, verbose_name='user_name'),
        ),
    ]
